# .github/workflows/ci.yml

name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  TEST_OTP_VERSION: '29'

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: '27'
            rebar3: '3.25.1'
          - otp: '28'
            rebar3: '3.25.1'
          - otp: '29'
            rebar3: '3.27.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Erlang and Rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}

      - name: Compile
        run: rebar3 compile

      - name: Libnt code
        run: rebar3 lint

      - name: Run EUnit
        if: "${{ matrix.otp == env.TEST_OTP_VERSION }}"
        run: rebar3 eunit --cover

      - name: Creates Cobertura coverage report
        run: rebar3 covertool generate

      - name: Upload coverage to Codecov
        if: "${{ matrix.otp == env.TEST_OTP_VERSION }}"
        uses: codecov/codecov-action@v7
        with:
          files: _build/test/covertool/dbus.covertool.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Cache Dialyzer PLT
      #   if: "${{ matrix.otp == env.TEST_OTP_VERSION }}"
      #   uses: actions/cache@v6
      #   with:
      #     path: |
      #       .*.plt
      #       .*.plt.hash
      #     key: ${{ runner.os }}-otp${{ matrix.otp }}-dialyzer-${{ hashFiles('Makefile', 'erlang.mk') }}
      #     restore-keys: |
      #       ${{ runner.os }}-otp${{ matrix.otp }}-dialyzer-

      # - name: Dialyzer
      #   if: "${{ matrix.otp == env.TEST_OTP_VERSION }}"
      #   run: make dialyze
